<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ZenlessZoneZeroOneDragonAdapter</AssemblyName>
    <RootNamespace>ZenlessZoneZeroOneDragonAdapter</RootNamespace>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\NexusPipeline.csproj" />
  </ItemGroup>

</Project>
