<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>NexusPipeline.Plugin.Abstractions</RootNamespace>
    <AssemblyName>NexusPipeline.Plugin.Abstractions</AssemblyName>
    <Version>1.2.0</Version>
  </PropertyGroup>

</Project>
