<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>nexus-pipeline</AssemblyName>
    <RootNamespace>NexusPipeline</RootNamespace>
    <Version>0.10.4</Version>
    <InvariantGlobalization>false</InvariantGlobalization>
    <NoWarn>CA1416</NoWarn>
    <ApplicationIcon>NexusPipeline.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="..\tests\NexusPipeline.Tests\**" />
    <Compile Remove="NexusPipeline.Plugin.Abstractions\**" />
    <None Include="..\tests\NexusPipeline.Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="NexusPipeline.Plugin.Abstractions\NexusPipeline.Plugin.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Jint" Version="4.2.2" />
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="NexusPipeline.Tests" />
  </ItemGroup>

</Project>
